### PR TITLE
been long time since i coded just trying to get a few things finished not sure they are done right sorry

### PR DESCRIPTION
**Pull request by crazywm**

### CODE REVIEW

**Comment by h1262216** [comment]
thanks!
in the long run, I'd like to move more of this to the xml files, and potentially lua scripts, but for now this is fine.

**Comment by crazywm** [comment]
Not good at coding really so this is what I can do. I hope to do some more loose end stuff I left maybe add more job events and the such. Gotta figure the xml out

**Comment by h1262216** [comment]
If you want something a bit easier than the C++ stuff, I'd recommend the lua scripting. If you'd like to continue working on the free-time events, I could just make a new "freetime" trigger for a corresponding lua event, and then just trigger this from the free-time job. 
Now that I've written that out, it actually sounds like a pretty good idea. I don't think all the things that are happening currently in the free time events are supported by lua, so its probably best to start with a few sub-events.

**Comment by h1262216** [comment]
Update: A few of the free-time events are now based on lua scripts. A few more could probably be ported easily, I just haven't had the time yet.

**Pull request merged**
