### PR TITLE
Reads gang names line by line...

### PR DESCRIPTION
**Pull request by UseAfterFree-177**
...not word by word. Most names in the list are two words.

### CODE REVIEW

**Comment by h1262216** [comment]
is there any reason why we can't use `std::getline` here?

**Comment by UseAfterFree-177** [comment]
`getline()` doesn't really support multiple end-of-line styles. The best you can do is to pick one single alternate end-of-line char at the call site. (And it wants a fixed-size buffer, but that's not a problem...unless I decide I want to grow it.)

**Comment by h1262216** [comment]
but aren't we opening the file in text mode, and thus getting normalized line endings?

**Comment by UseAfterFree-177** [comment]
Only on Windows. On Linux, there's no difference between text and binary mode.

**Comment by h1262216** [comment]
right, so we'd be in trouble for files that are neither handled through git nor edited on the local system or on linux, which I guess may be unlikely, but not entirely impossible. 

I'm not 100% convinced we really need this, but if you want to keep it, can you please move it to the utility functions (e.g. `utils/string.hpp` maybe) so it can be reused. I think cNameList is doing basically the same thing (and the two codes should probably be unified), so that then should also switch from std::getline to this new readline.

**Comment by UseAfterFree-177** [comment]
When I tried to use `getline()` the debugger showed me a trailing \r on every name I read from HiredGangNames.txt; so we'd also in trouble with files that do come through git :disappointed: .

I'll move my `readline()` to one of the `utils/` files (`string.hpp` sound ok), and while I'm at it, I'll templatize it. And I'll have a look at `cNameList` as well.

**Comment by UseAfterFree-177** [comment]
`readline()` moved, `cNameList::load()` updated. No templating, though (I tried but things broke).

**Comment by h1262216** [comment]
looks good. I'll move the implementation of readline into the cpp file, though

**Pull request merged**
